  version: 2.2
  hooks:
    - type: pre-commit
      actions:
        - name: "Git Pull (Ensure there are no upstream changes that are not local)"
          exec: git
          args: ["pull"]
        - name: "Go Tidy"
          exec: go
          args: ["mod", "tidy"]
        - name: "Update all go dependencies to latest"
          exec: go
          args: ["get", "-u", "./..."]
        - name: "Run gofmt to format the code"
          exec: gofmt
          args: ["-w", "*/*.go"]
        - name: "Add all changed files during the pre-commit stage"
          exec: git
          args: ["add", "."]
        - name: Hinge
          url: https://github.com/devops-kung-fu/hinge/releases/download/v0.0.9/hinge-0.0.9-linux-amd64
          args: ["."]
        - name: "cyclone-dx: Generate a Software Bill of Materials (SBoM)"
          exec: cyclonedx-gomod
          args: ["-json", "-output", "sbom.json", "-std", "-licenses"]
